# Whale short URL rewrite example.
# Add this inside the server block that serves MediaWiki.

location ~ ^/s/([0-9A-Za-z]+)$ {
	rewrite ^/s/([0-9A-Za-z]+)$ /index.php?title=Special:WhaleShortUrl/$1 last;
}
